name: upload files to s3
on:
  push:
    branches:
      - main

jobs:
  upload-file-to-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        
    - name: run npm install and npm run build
      run: |
        npm install
        npm run build

    - name: Upload files to s3
      run: |
        
        aws s3 sync /build s3://frontend-p3-kevinzhou309 --recursive
        
